language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
    secure: xYTT7iKG/1nnl15WCZHv8190UkqMsvVbSv9svokN3Rg71jbYIN1TZ921h0N7B3L6OiiPr7VzpXcaZtGl1+8aCASpl7ytekbrxSupMaXkZN/i2ASiw5+WKNa+8+gEXxxgtGltO1olhd/trVbSrbauelZyLORvuCTH780O0zrd074=
