language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
    secure: mPmF/3N5HixBIzKMkDul0R3soqa3DMoqAIuAZCwQ6wG9z2IufWPgaOrhg8Kjc5XObECq7pdUUTX5cFLqHlc7txHVqPaVIE1Kq1EnBHL+bTbJif4hb+aSeDpYZqNOrwHlQ2wnlaXvkTFUjxhOXWlPqst/IhPUTQkX3+ifZNdeOKQ=
