language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
    secure: qut3lG6g9zgRCyhsGlGzUtwWN/r5XU/1tXJf2nLINiY+cguF7Ht9BAJLdfoWhUp9O4juxe92kk/Bo5deq2iNNtUpPLwIYujhCRQQOSnoXqmejTwFB4Ba9Psafbxs2F+EQQ/2XC6U0OsP9ZE32kBB8SbzVuEsT12psE+x426WnNI=
